---
--- Generated by Luanalysis
--- Created by DAIJUNQIANG.
--- DateTime: 2023/2/12 15:47
--- lua脚本 进行redis缓存热点数据（优惠券秒杀）的操作 使用lua脚本可以保证原子性
---
-- 1.参数列表：
--1.1.优惠券id
local voucherId = ARGV[1]

--1.2.用户id
local userId = ARGV[2]

--1.3.订单id
local orderId = ARGV[3]

--2.数据Key
--2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
--2.2 订单key
local orderKey = 'seckill:order:' .. voucherId


-- 3.脚本业务
-- 3.1.判断库存是否充足
if (tonumber(redis.call('get',stockKey)) <= 0) then
    --库存不足返回1
    return 1
end
-- 3.2.判断用户是否已经下了订单
if(redis.call('sismember',orderKey,userId)== 1) then
    --3.3.用户重复下单 返回2
    return 2
end

--3.4.扣库存 incrby stockKey -1
redis.call('incrby',stockKey,-1);
--3.5.下单（保存用户） sadd orderKey userId
redis.call('sadd',orderKey,userId);
--3.6.发送消息到队列当中 XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId);

return 0